### ISSUE TITLE
start-vswitch.sh is incompatible with KVM-RT

### ISSUE THREAD

**Issue by k-rister** [atheurer/dpdk-rhel-perf-tools#21]
https://github.com/atheurer/dpdk-rhel-perf-tools/blob/491056e94a9568a855ed4f6229a2f5a1e266b421/start-vswitch.sh#L63

The tuned.non_isolcpus parameter is only present in the cpu-partitioning tuned profile and not the realtime-virtual-[host|guest] profiles.

**Comment by atheurer** [comment]
OK, I guess we'll also have to check for /sys/devices/system/cpu/isolated

**Comment by k-rister** [comment]
Ok, I'm working on that.  Isn't this line irrelevant:

https://github.com/atheurer/dpdk-rhel-perf-tools/blob/master/start-vswitch.sh#L73

**Comment by atheurer** [comment]
Yes.  I must have missed removing that
